version: '3.9'
services:
  data-mining-project-database:
    image: postgres:latest
    container_name: data-mining-db
    environment:
      - POSTGRES_DB=data-mining-project
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./lib/initdb/1-init-table.sql:/docker-entrypoint-initdb.d/1-init-table.sql
      - ./lib/initdb/2-insert-data.sql:/docker-entrypoint-initdb.d/2-insert-data.sql
      - ./database:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: always