version: '3.9'
services:
  data-mining-project-database:
    image: postgres:latest
    container_name: data-mining-db
    environment:
      - POSTGRES_DB=data-mining-project
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./lib/1-init-table.sql:/docker-entrypoint-initdb.d/1-init-table.sql
    ports:
      - "5432:5432"
    restart: always